name: Run Test Suite

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout code.
      - uses: actions/checkout@v3

      # Set up Python.
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Cache the poetry installation so it doesn't have to be reinstalled every time.
      - name: cache poetry install
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-1.2.2-0

      # Use a third party action to install poetry if needed.
      - uses: snok/install-poetry@v1
        with:
          version: 1.2.2
          virtualenvs-create: true
          virtualenvs-in-project: true

      # Cache dependencies.
      - name: cache deps
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: .venv
          key: pydeps-${{ hashFiles('**/poetry.lock') }}

      # Install the dependencies if not restored from cache.
      - run: poetry install --no-interaction --no-root
        if: steps.cache-deps.outputs.cache-hit != 'true'

      # Install this project.
      - run: poetry install --no-interaction

      # Run the tests.
      - run: poetry run pytest

